db:
 setwd : /home/share/Jonathan/NCSU_Elanco/
 vis_dir : Visualizations/Dada2
 out_dir : Output/Dada2
 fastq_path : Data/Raw_Seqs
 f_fastq_format : _R1_001.fastq
 r_fastq_format : _R2_001.fastq
 f_truncLen : 150
 r_truncLeng : 149
 maxEE : 2
 maxN : 0
 f_primer_len : 19
 r_primer_len : 20
